<?php
/**
 * BrandApi
 * PHP version 7.3
 *
 * @category Class
 * @package  AkeneoPresales\DescrbAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * {descrb}
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AkeneoPresales\DescrbAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use AkeneoPresales\DescrbAPI\Client\ApiException;
use AkeneoPresales\DescrbAPI\Client\Configuration;
use AkeneoPresales\DescrbAPI\Client\HeaderSelector;
use AkeneoPresales\DescrbAPI\Client\ObjectSerializer;

/**
 * BrandApi Class Doc Comment
 *
 * @category Class
 * @package  AkeneoPresales\DescrbAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BrandApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createBrandAdApiV1BrandPost
     *
     * Create Brand Ad
     *
     * @param  \SplFileObject $image Image File (optional)
     * @param  string $photo_url Photo URL (optional, default to '')
     * @param  string $brand_name Product Name (optional, default to '')
     * @param  int $length Numer of Tokens (optional, default to 512)
     * @param  string $language Supported languages: en,de,fr,es,ro,pl (optional, default to 'pl')
     * @param  string $data_language Data Source Language (optional, default to '')
     * @param  string $language_style Choose between Neutral, Casual, Specialist (optional, default to 'Neutral')
     *
     * @throws \AkeneoPresales\DescrbAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return mixed|\AkeneoPresales\DescrbAPI\Client\Model\HTTPValidationError
     */
    public function createBrandAdApiV1BrandPost($image = null, $photo_url = '', $brand_name = '', $length = 512, $language = 'pl', $data_language = '', $language_style = 'Neutral')
    {
        list($response) = $this->createBrandAdApiV1BrandPostWithHttpInfo($image, $photo_url, $brand_name, $length, $language, $data_language, $language_style);
        return $response;
    }

    /**
     * Operation createBrandAdApiV1BrandPostWithHttpInfo
     *
     * Create Brand Ad
     *
     * @param  \SplFileObject $image Image File (optional)
     * @param  string $photo_url Photo URL (optional, default to '')
     * @param  string $brand_name Product Name (optional, default to '')
     * @param  int $length Numer of Tokens (optional, default to 512)
     * @param  string $language Supported languages: en,de,fr,es,ro,pl (optional, default to 'pl')
     * @param  string $data_language Data Source Language (optional, default to '')
     * @param  string $language_style Choose between Neutral, Casual, Specialist (optional, default to 'Neutral')
     *
     * @throws \AkeneoPresales\DescrbAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of mixed|\AkeneoPresales\DescrbAPI\Client\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function createBrandAdApiV1BrandPostWithHttpInfo($image = null, $photo_url = '', $brand_name = '', $length = 512, $language = 'pl', $data_language = '', $language_style = 'Neutral')
    {
        $request = $this->createBrandAdApiV1BrandPostRequest($image, $photo_url, $brand_name, $length, $language, $data_language, $language_style);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('mixed' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'mixed', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 422:
                    if ('\AkeneoPresales\DescrbAPI\Client\Model\HTTPValidationError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\AkeneoPresales\DescrbAPI\Client\Model\HTTPValidationError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'mixed';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'mixed',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AkeneoPresales\DescrbAPI\Client\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createBrandAdApiV1BrandPostAsync
     *
     * Create Brand Ad
     *
     * @param  \SplFileObject $image Image File (optional)
     * @param  string $photo_url Photo URL (optional, default to '')
     * @param  string $brand_name Product Name (optional, default to '')
     * @param  int $length Numer of Tokens (optional, default to 512)
     * @param  string $language Supported languages: en,de,fr,es,ro,pl (optional, default to 'pl')
     * @param  string $data_language Data Source Language (optional, default to '')
     * @param  string $language_style Choose between Neutral, Casual, Specialist (optional, default to 'Neutral')
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createBrandAdApiV1BrandPostAsync($image = null, $photo_url = '', $brand_name = '', $length = 512, $language = 'pl', $data_language = '', $language_style = 'Neutral')
    {
        return $this->createBrandAdApiV1BrandPostAsyncWithHttpInfo($image, $photo_url, $brand_name, $length, $language, $data_language, $language_style)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createBrandAdApiV1BrandPostAsyncWithHttpInfo
     *
     * Create Brand Ad
     *
     * @param  \SplFileObject $image Image File (optional)
     * @param  string $photo_url Photo URL (optional, default to '')
     * @param  string $brand_name Product Name (optional, default to '')
     * @param  int $length Numer of Tokens (optional, default to 512)
     * @param  string $language Supported languages: en,de,fr,es,ro,pl (optional, default to 'pl')
     * @param  string $data_language Data Source Language (optional, default to '')
     * @param  string $language_style Choose between Neutral, Casual, Specialist (optional, default to 'Neutral')
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createBrandAdApiV1BrandPostAsyncWithHttpInfo($image = null, $photo_url = '', $brand_name = '', $length = 512, $language = 'pl', $data_language = '', $language_style = 'Neutral')
    {
        $returnType = 'mixed';
        $request = $this->createBrandAdApiV1BrandPostRequest($image, $photo_url, $brand_name, $length, $language, $data_language, $language_style);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createBrandAdApiV1BrandPost'
     *
     * @param  \SplFileObject $image Image File (optional)
     * @param  string $photo_url Photo URL (optional, default to '')
     * @param  string $brand_name Product Name (optional, default to '')
     * @param  int $length Numer of Tokens (optional, default to 512)
     * @param  string $language Supported languages: en,de,fr,es,ro,pl (optional, default to 'pl')
     * @param  string $data_language Data Source Language (optional, default to '')
     * @param  string $language_style Choose between Neutral, Casual, Specialist (optional, default to 'Neutral')
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createBrandAdApiV1BrandPostRequest($image = null, $photo_url = '', $brand_name = '', $length = 512, $language = 'pl', $data_language = '', $language_style = 'Neutral')
    {

        $resourcePath = '/api/v1/brand/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        if ($image !== null) {
            $multipart = true;
            $formParams['image'] = [];
            $paramFiles = is_array($image) ? $image : [$image];
            foreach ($paramFiles as $paramFile) {
                $formParams['image'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }
        // form params
        if ($photo_url !== null) {
            $formParams['photo_url'] = ObjectSerializer::toFormValue($photo_url);
        }
        // form params
        if ($brand_name !== null) {
            $formParams['brand_name'] = ObjectSerializer::toFormValue($brand_name);
        }
        // form params
        if ($length !== null) {
            $formParams['length'] = ObjectSerializer::toFormValue($length);
        }
        // form params
        if ($language !== null) {
            $formParams['language'] = ObjectSerializer::toFormValue($language);
        }
        // form params
        if ($data_language !== null) {
            $formParams['data_language'] = ObjectSerializer::toFormValue($data_language);
        }
        // form params
        if ($language_style !== null) {
            $formParams['language_style'] = ObjectSerializer::toFormValue($language_style);
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['multipart/form-data']
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation reviewBrandDescriptionApiV1BrandBrandDescriptionIdReviewPost
     *
     * Review Brand Description
     *
     * @param  string $brand_description_id brand_description_id (required)
     * @param  \AkeneoPresales\DescrbAPI\Client\Model\BrandDescriptionUpdate $brand_description_update brand_description_update (required)
     *
     * @throws \AkeneoPresales\DescrbAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \AkeneoPresales\DescrbAPI\Client\Model\BrandDescriptionUpdate|\AkeneoPresales\DescrbAPI\Client\Model\HTTPValidationError
     */
    public function reviewBrandDescriptionApiV1BrandBrandDescriptionIdReviewPost($brand_description_id, $brand_description_update)
    {
        list($response) = $this->reviewBrandDescriptionApiV1BrandBrandDescriptionIdReviewPostWithHttpInfo($brand_description_id, $brand_description_update);
        return $response;
    }

    /**
     * Operation reviewBrandDescriptionApiV1BrandBrandDescriptionIdReviewPostWithHttpInfo
     *
     * Review Brand Description
     *
     * @param  string $brand_description_id (required)
     * @param  \AkeneoPresales\DescrbAPI\Client\Model\BrandDescriptionUpdate $brand_description_update (required)
     *
     * @throws \AkeneoPresales\DescrbAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \AkeneoPresales\DescrbAPI\Client\Model\BrandDescriptionUpdate|\AkeneoPresales\DescrbAPI\Client\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function reviewBrandDescriptionApiV1BrandBrandDescriptionIdReviewPostWithHttpInfo($brand_description_id, $brand_description_update)
    {
        $request = $this->reviewBrandDescriptionApiV1BrandBrandDescriptionIdReviewPostRequest($brand_description_id, $brand_description_update);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\AkeneoPresales\DescrbAPI\Client\Model\BrandDescriptionUpdate' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\AkeneoPresales\DescrbAPI\Client\Model\BrandDescriptionUpdate', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 422:
                    if ('\AkeneoPresales\DescrbAPI\Client\Model\HTTPValidationError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\AkeneoPresales\DescrbAPI\Client\Model\HTTPValidationError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\AkeneoPresales\DescrbAPI\Client\Model\BrandDescriptionUpdate';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AkeneoPresales\DescrbAPI\Client\Model\BrandDescriptionUpdate',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AkeneoPresales\DescrbAPI\Client\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation reviewBrandDescriptionApiV1BrandBrandDescriptionIdReviewPostAsync
     *
     * Review Brand Description
     *
     * @param  string $brand_description_id (required)
     * @param  \AkeneoPresales\DescrbAPI\Client\Model\BrandDescriptionUpdate $brand_description_update (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function reviewBrandDescriptionApiV1BrandBrandDescriptionIdReviewPostAsync($brand_description_id, $brand_description_update)
    {
        return $this->reviewBrandDescriptionApiV1BrandBrandDescriptionIdReviewPostAsyncWithHttpInfo($brand_description_id, $brand_description_update)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation reviewBrandDescriptionApiV1BrandBrandDescriptionIdReviewPostAsyncWithHttpInfo
     *
     * Review Brand Description
     *
     * @param  string $brand_description_id (required)
     * @param  \AkeneoPresales\DescrbAPI\Client\Model\BrandDescriptionUpdate $brand_description_update (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function reviewBrandDescriptionApiV1BrandBrandDescriptionIdReviewPostAsyncWithHttpInfo($brand_description_id, $brand_description_update)
    {
        $returnType = '\AkeneoPresales\DescrbAPI\Client\Model\BrandDescriptionUpdate';
        $request = $this->reviewBrandDescriptionApiV1BrandBrandDescriptionIdReviewPostRequest($brand_description_id, $brand_description_update);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'reviewBrandDescriptionApiV1BrandBrandDescriptionIdReviewPost'
     *
     * @param  string $brand_description_id (required)
     * @param  \AkeneoPresales\DescrbAPI\Client\Model\BrandDescriptionUpdate $brand_description_update (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function reviewBrandDescriptionApiV1BrandBrandDescriptionIdReviewPostRequest($brand_description_id, $brand_description_update)
    {
        // verify the required parameter 'brand_description_id' is set
        if ($brand_description_id === null || (is_array($brand_description_id) && count($brand_description_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $brand_description_id when calling reviewBrandDescriptionApiV1BrandBrandDescriptionIdReviewPost'
            );
        }
        // verify the required parameter 'brand_description_update' is set
        if ($brand_description_update === null || (is_array($brand_description_update) && count($brand_description_update) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $brand_description_update when calling reviewBrandDescriptionApiV1BrandBrandDescriptionIdReviewPost'
            );
        }

        $resourcePath = '/api/v1/brand/{brand_description_id}/review';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($brand_description_id !== null) {
            $resourcePath = str_replace(
                '{' . 'brand_description_id' . '}',
                ObjectSerializer::toPathValue($brand_description_id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($brand_description_update)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($brand_description_update));
            } else {
                $httpBody = $brand_description_update;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
