<?php
/**
 * BrandTemplateApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * {descrb}
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BrandTemplateApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BrandTemplateApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createTemplateApiV1BrandTemplatePost
     *
     * Create Template.
     *
     */
    public function testCreateTemplateApiV1BrandTemplatePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteTemplateApiV1BrandTemplateTemplateTemplateIdDelete
     *
     * Delete Template.
     *
     */
    public function testDeleteTemplateApiV1BrandTemplateTemplateTemplateIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for editTemplateApiV1BrandTemplateTemplateTemplateIdPatch
     *
     * Edit Template.
     *
     */
    public function testEditTemplateApiV1BrandTemplateTemplateTemplateIdPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readUserTemplatesApiV1BrandTemplateMyTemplatesGet
     *
     * Read User Templates.
     *
     */
    public function testReadUserTemplatesApiV1BrandTemplateMyTemplatesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
