<?php
/**
 * ProductApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * {descrb}
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createDemoProductAdApiV1ProductDemoPost
     *
     * Create Demo Product Ad.
     *
     */
    public function testCreateDemoProductAdApiV1ProductDemoPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createProductAdApiV1ProductPost
     *
     * Create Product Ad.
     *
     */
    public function testCreateProductAdApiV1ProductPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for editBrandDescriptionApiV1ProductBrandDescriptionIdPatch
     *
     * Edit Brand Description.
     *
     */
    public function testEditBrandDescriptionApiV1ProductBrandDescriptionIdPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for editDescriptionApiV1ProductDescriptionDescriptionIdPatch
     *
     * Edit Description.
     *
     */
    public function testEditDescriptionApiV1ProductDescriptionDescriptionIdPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for editHistoryDescriptionApiV1ProductHistoryDescriptionIdPatch
     *
     * Edit History Description.
     *
     */
    public function testEditHistoryDescriptionApiV1ProductHistoryDescriptionIdPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for exportChosenToCsvApiV1ProductExportChosenPut
     *
     * Export Chosen To Csv.
     *
     */
    public function testExportChosenToCsvApiV1ProductExportChosenPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for exportPageToCsvAdminPanelApiV1ProductAdminExportCurrentPageGet
     *
     * Export Page To Csv Admin Panel.
     *
     */
    public function testExportPageToCsvAdminPanelApiV1ProductAdminExportCurrentPageGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for exportPageToCsvApiV1ProductExportCurrentPageGet
     *
     * Export Page To Csv.
     *
     */
    public function testExportPageToCsvApiV1ProductExportCurrentPageGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for exportToCsvAdminPanelApiV1ProductAdminExportAllGet
     *
     * Export To Csv Admin Panel.
     *
     */
    public function testExportToCsvAdminPanelApiV1ProductAdminExportAllGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for exportToCsvApiV1ProductExportAllGet
     *
     * Export To Csv.
     *
     */
    public function testExportToCsvApiV1ProductExportAllGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDescriptionApiV1ProductDescriptionIdGet
     *
     * Get Description.
     *
     */
    public function testGetDescriptionApiV1ProductDescriptionIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readAllProductDescriptionsApiV1ProductAllGet
     *
     * Read All Product Descriptions.
     *
     */
    public function testReadAllProductDescriptionsApiV1ProductAllGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readUserProductDescriptionsApiV1ProductMyReviewsGet
     *
     * Read User Product Descriptions.
     *
     */
    public function testReadUserProductDescriptionsApiV1ProductMyReviewsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for regenerateBrandDescriptionApiV1ProductRegenerateBrandDescriptionDescriptionIdPost
     *
     * Regenerate Brand Description.
     *
     */
    public function testRegenerateBrandDescriptionApiV1ProductRegenerateBrandDescriptionDescriptionIdPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for regenerateDescriptionApiV1ProductRegenerateDescriptionDescriptionIdPost
     *
     * Regenerate Description.
     *
     */
    public function testRegenerateDescriptionApiV1ProductRegenerateDescriptionDescriptionIdPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for regenerateEmptyApiV1ProductRegenerateEmptyDescriptionDescriptionIdPost
     *
     * Regenerate Empty.
     *
     */
    public function testRegenerateEmptyApiV1ProductRegenerateEmptyDescriptionDescriptionIdPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for regenerateHistoryDescriptionApiV1ProductRegenerateHistoryDescriptionDescriptionIdPost
     *
     * Regenerate History Description.
     *
     */
    public function testRegenerateHistoryDescriptionApiV1ProductRegenerateHistoryDescriptionDescriptionIdPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for regenerateTechnologyApiV1ProductRegenerateTechnologiesDescriptionDescriptionIdPost
     *
     * Regenerate Technology.
     *
     */
    public function testRegenerateTechnologyApiV1ProductRegenerateTechnologiesDescriptionDescriptionIdPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reviewBrandDescriptionApiV1ProductBrandDescriptionIdReviewPost
     *
     * Review Brand Description.
     *
     */
    public function testReviewBrandDescriptionApiV1ProductBrandDescriptionIdReviewPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reviewDescriptionApiV1ProductDescriptionDescriptionIdReviewPost
     *
     * Review Description.
     *
     */
    public function testReviewDescriptionApiV1ProductDescriptionDescriptionIdReviewPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reviewHistoryDescriptionApiV1ProductHistoryDescriptionIdReviewPost
     *
     * Review History Description.
     *
     */
    public function testReviewHistoryDescriptionApiV1ProductHistoryDescriptionIdReviewPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for translateDescriptionApiV1ProductTranslateDescriptionDescriptionIdPost
     *
     * Translate Description.
     *
     */
    public function testTranslateDescriptionApiV1ProductTranslateDescriptionDescriptionIdPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
