<?php
/**
 * UsersApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * {descrb}
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UsersApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UsersApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for changeUserLanguageApiV1UsersLanguagePatch
     *
     * Change User Language.
     *
     */
    public function testChangeUserLanguageApiV1UsersLanguagePatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createTrialSubApiV1UsersGetTrialPatch
     *
     * Create Trial Sub.
     *
     */
    public function testCreateTrialSubApiV1UsersGetTrialPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createUserApiV1UsersCreatePost
     *
     * Create User.
     *
     */
    public function testCreateUserApiV1UsersCreatePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createUserProfileApiV1UsersPost
     *
     * Create User Profile.
     *
     */
    public function testCreateUserProfileApiV1UsersPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for endActiveTrialApiV1UsersEndCurrentTrialPatch
     *
     * End Active Trial.
     *
     */
    public function testEndActiveTrialApiV1UsersEndCurrentTrialPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateReportApiV1UsersReportGet
     *
     * Generate Report.
     *
     */
    public function testGenerateReportApiV1UsersReportGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for markTrialNotificationAsSeenApiV1UsersNotificationAboutExpirePost
     *
     * Mark Trial Notification As Seen.
     *
     */
    public function testMarkTrialNotificationAsSeenApiV1UsersNotificationAboutExpirePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchUserApiV1UsersPatch
     *
     * Patch User.
     *
     */
    public function testPatchUserApiV1UsersPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readAllUsersApiV1UsersAllGet
     *
     * Read All Users.
     *
     */
    public function testReadAllUsersApiV1UsersAllGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readUserApiV1UsersGet
     *
     * Read User.
     *
     */
    public function testReadUserApiV1UsersGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readUserApiV1UsersPaymentsInfoGet
     *
     * Read User.
     *
     */
    public function testReadUserApiV1UsersPaymentsInfoGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readUserDescriptionsApiV1UsersUserIdDescriptionsGet
     *
     * Read User Descriptions.
     *
     */
    public function testReadUserDescriptionsApiV1UsersUserIdDescriptionsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readUserNotReviewedDescriptionsApiV1UsersUserIdNotReviewedDescriptionsGet
     *
     * Read User Not Reviewed Descriptions.
     *
     */
    public function testReadUserNotReviewedDescriptionsApiV1UsersUserIdNotReviewedDescriptionsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readUserNotSeenDescriptionsApiV1UsersUserIdNotSeenDescriptionsGet
     *
     * Read User Not Seen Descriptions.
     *
     */
    public function testReadUserNotSeenDescriptionsApiV1UsersUserIdNotSeenDescriptionsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for requestNewTotpApiV1UsersNewTotpPost
     *
     * Request New Totp.
     *
     */
    public function testRequestNewTotpApiV1UsersNewTotpPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for testEndpointApiV1UsersTesterGet
     *
     * Test Endpoint.
     *
     */
    public function testTestEndpointApiV1UsersTesterGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for toggleStateApiV1UsersToggleStatePost
     *
     * Toggle State.
     *
     */
    public function testToggleStateApiV1UsersToggleStatePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateUserApiV1UsersPut
     *
     * Update User.
     *
     */
    public function testUpdateUserApiV1UsersPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for validateEmailApiV1UsersValidateEmailPost
     *
     * Validate Email.
     *
     */
    public function testValidateEmailApiV1UsersValidateEmailPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
